### ISSUE TITLE
Allow help to wrap over multiple lines

### ISSUE THREAD

**Issue by chrisduerr** [chrisduerr/sketch#16]
Originally the help was just supposed to be one or two buttons that should always fit on the screen, but with increasing complexity comes an increasing amount of bindings one should know about.

To make it possible to run sketch with a small terminal window, there should be a system in place so these help actions can automatically flow into the next line.

**Comment by kchibisov** [comment]
I think you can show help by pressing some hotkey. I think pulsemixer does that, when you press `?` it shows all the bindings.

![picture](https://user-images.githubusercontent.com/27620401/102033409-69a55e00-3dcc-11eb-8125-dc8df894c7bd.png)

**Comment by chrisduerr** [comment]
Yeah, that's one thing I've considered actually. Though you'd still need to show the binding for the help.

**Comment by kchibisov** [comment]
yeah, but it's pretty short, and removing it on a very small window size won't hurt, since it's just one binding which can be memorized easily.
