### ISSUE TITLE
Provide alternative bindings to change brush size

### ISSUE THREAD

**Issue by kchibisov** [chrisduerr/sketch#3]
Mouse 4 and 5 buttons are not present on, I think, mostly all laptops and  also some mice don't have them, so providing an alternative bindings to do so would be nice.

**Comment by kchibisov** [comment]
Ah, 4 and 5 are for mouse scroll wheel, so it makes sense for them to be that way, though it'd be nice to an information somewhere about those bindings, since I thought for whatever reason that those are side buttons.

**Comment by chrisduerr** [comment]
Yeah, showing those in the help would make sense. It might also be useful to bind ctrl +/-, but those have a good chance of being bound in the terminal already (at least in Alacritty they are).
