### ISSUE TITLE
Inablity to type 'q' due to collision with exit shortcut

### ISSUE THREAD

**Issue by kchibisov** [chrisduerr/sketch#4]
One could think that `Ctrl Q` can be used, however it's not the case, since it's used for resuming the terminal most of the time, thus it's captured. I have a feeling that there's a way to disable `Ctrl q/s` just for an application, since neovim does that somehow.

**Comment by chrisduerr** [comment]
Oh you're right. I've considered this for the character picker which is why `Q` doesn't quit that dialog, but the typing itself of course doesn't allow for Q like this.
